### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by zero5enpai** [taichikuji/discordid#36]
Website's down. 
Is this officially dead? Any recommendations for similar services? 
I used it to link my discord profile to people which I dont share a server with so the usual profile linking wont work.

**Comment by zero5enpai** [comment]
Yeah nvm, mb.
Its getting blocked locally for me in firefox. 
Seems that only the browser blocks any connection with https://discordid.netlify.app/... 
For the record, I'm getting a website not found.

**Comment by taichikuji** [comment]
This seems to be an issue with the website being wrongly reported in the safebrowsing tool by Firefox which is also used by Google:

https://safebrowsing.google.com/safebrowsing/report_error/?tpl=mozilla&hl=en

If you report the website as wrongly marked as phishing, perhaps it can help not only you but the rest of the people that are affected by this.
